sonar.projectKey=vinjatovix_agro-front
sonar.organization=vinjatovix

sonar.sources=src
sonar.tests=tests

sonar.test.inclusions=tests/**/*.ts,tests/**/*.tsx

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.exclusions=dist/**,coverage/**,src/generated/**,**/*.d.ts,**/main.tsx,**/vite-env.d.ts